name: Contiuous Deployment

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build And Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: yarn

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test --watchAll=false

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop')

    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set QA Environment
        run: echo "::set-env name=ENVIRONMENT::develop"

      - name: Set Production Environment
        if: github.ref == 'refs/heads/master'
        run: echo "::set-env name=ENVIRONMENT::master"

      - name: Add Remote Origin
        run: git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/component-lib-$ENVIRONMENT.git

      - name: Unshallow Repo
        run: git filter-branch -- --all

      - name: Push to Heroku
        run: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/component-lib-$ENVIRONMENT.git $GITHUB_SHA:refs/heads/master
